-- Script généré par WINDEV le 25/05/2026 13:49:48
-- Tables de l'analyse GIES.wda
-- pour PostgreSQL

-- Création de la table ANNEE
CREATE TABLE "ANNEE" (
    "ANNEE" INTEGER  UNIQUE  DEFAULT 0);

-- Création de la table ANNEESCOLAIRE
CREATE TABLE "ANNEESCOLAIRE" (
    "IDANNEESCOLAIRE" SERIAL8  PRIMARY KEY ,
    "ANNEEDEBUT" INTEGER DEFAULT 0,
    "ANNEEFIN" INTEGER DEFAULT 0,
    "ANNEESCOLAIRE" VARCHAR(50) ,
    "STATUS" SMALLINT DEFAULT 0,
    "NBREINSCRIT" INTEGER DEFAULT 0,
    "NBREMOISETU" INTEGER DEFAULT 0,
    "NBREFILLES" INTEGER DEFAULT 0,
    "NBREGARCONS" INTEGER DEFAULT 0);
CREATE INDEX "WDIDX_ANNEESCOLAIRE_ANNEESCOLAIRE" ON "ANNEESCOLAIRE" ("ANNEESCOLAIRE");
CREATE INDEX "WDIDX_ANNEESCOLAIRE_STATUS" ON "ANNEESCOLAIRE" ("STATUS");

-- Création de la table ELEVES
CREATE TABLE "ELEVES" (
    "IDELEVES" SERIAL8  PRIMARY KEY ,
    "N_MATRICULE" VARCHAR(100) ,
    "NOM" VARCHAR(80) ,
    "PRENOM" VARCHAR(100) ,
    "DATENAISS" DATE ,
    "AGES" INTEGER DEFAULT 0,
    "LIEUNAISS" VARCHAR(50) ,
    "PARENTPERE" VARCHAR(150) ,
    "PARENTMERE" VARCHAR(50) ,
    "TELEPHONEPARENT" VARCHAR(100) ,
    "TELEPHONEELEVE" VARCHAR(50) ,
    "TUTEUR" VARCHAR(100) ,
    "TELEPHONETUTELLE" VARCHAR(50) ,
    "ADRESSPARENT_OU_TUTEUR" VARCHAR(200) ,
    "NATIONALITE" VARCHAR(50) ,
    "IDANNEESCOLAIRE" BIGINT DEFAULT 0,
    "STATUS" SMALLINT DEFAULT 0,
    "IDCLASSES" BIGINT DEFAULT 0,
    "LOGIN" VARCHAR(50)  UNIQUE ,
    "MOTDEPASSE" VARCHAR(50) ,
    "PHOTO" BYTEA ,
    "N_ELEVE" VARCHAR(50)  UNIQUE ,
    "SEXE" SMALLINT DEFAULT 0,
    "EMAIL" VARCHAR(50) ,
    "ANTECEDENT" VARCHAR(50) ,
    "PROFESSIONPERE" VARCHAR(50) ,
    "PROFESSIONMERE" VARCHAR(50) ,
    "IDGROUPE" BIGINT DEFAULT 0,
    "LIENPARENTE" VARCHAR(50) ,
    "NUM_ACTENAISS" VARCHAR(50) ,
    "POIDS" VARCHAR(50) ,
    "TAILLEE" VARCHAR(50) ,
    "IDCATEGORIE" BIGINT DEFAULT 0,
    "DERNIERECOLESUIVIE" VARCHAR(100) ,
    "MOTIFDEPART" VARCHAR(50) ,
    "ETATDERNIER" SMALLINT DEFAULT 0,
    "APRECIATIONDIRECTEUR" VARCHAR(50) ,
    "IDNIVEAU" BIGINT DEFAULT 0);

-- Création de la table CLASSES
CREATE TABLE "CLASSES" (
    "IDCLASSES" SERIAL8  PRIMARY KEY ,
    "CLASSES" VARCHAR(50) ,
    "IDNIVEAU" BIGINT ,
    "FILIERE" VARCHAR(50) ,
    "NBRENOTECLASSE" SMALLINT DEFAULT 0,
    "IDENSEIGNANT" BIGINT DEFAULT 0);

-- Création de la table ENSEIGNANT
CREATE TABLE "ENSEIGNANT" (
    "IDENSEIGNANT" SERIAL8  PRIMARY KEY ,
    "NOMPRENOM" VARCHAR(100) ,
    "PRENOM" VARCHAR(100) ,
    "DATECREATION" DATE ,
    "SPECIALITE" VARCHAR(50) ,
    "SEXE" SMALLINT DEFAULT 0,
    "DATENAISS" DATE ,
    "LIEUNAISS" VARCHAR(50) ,
    "ADRESSE" VARCHAR(100) ,
    "TELEPHONE" VARCHAR(50) ,
    "STATUS" VARCHAR(50) ,
    "AUTRESPECIALITE" VARCHAR(50) ,
    "LOGIN" VARCHAR(50)  UNIQUE ,
    "MOTDEPASSE" VARCHAR(50) ,
    "EMAIL" VARCHAR(50) ,
    "PHOTO" BYTEA ,
    "DIPLOME" VARCHAR(50) ,
    "IDNIVEAU" BIGINT DEFAULT 0,
    "SUPPRIMER" BOOL DEFAULT false);

-- Création de la table NIVEAU
CREATE TABLE "NIVEAU" (
    "IDNIVEAU" SERIAL8  PRIMARY KEY ,
    "NIVEAU" VARCHAR(50) ,
    "PRISEENCOMPTE" BOOL DEFAULT false,
    "IDUTILISATEURS" BIGINT DEFAULT 0);

-- Création de la table MATIERE
CREATE TABLE "MATIERE" (
    "IDMATIERE" SERIAL8  PRIMARY KEY ,
    "MATIERE" VARCHAR(100) );

-- Création de la table MATIEREENSEIGNE
CREATE TABLE "MATIEREENSEIGNE" (
    "IDMATIEREENSEIGNE" SERIAL8  PRIMARY KEY ,
    "COEFFICIENT" SMALLINT DEFAULT 0,
    "CATEGORIE" VARCHAR(50) ,
    "TYPEMATIERE" SMALLINT DEFAULT 0,
    "PRISEENCOMPTE" BOOL DEFAULT false,
    "IDCLASSES" BIGINT ,
    "IDMATIERE" BIGINT ,
    "NEUTRE" BOOL DEFAULT false);

-- Création de la table COURS
CREATE TABLE "COURS" (
    "IDCOURS" SERIAL8  PRIMARY KEY ,
    "IDMATIEREENSEIGNE" BIGINT ,
    "IDENSEIGNANT" BIGINT ,
    "IDANNEESCOLAIRE" BIGINT DEFAULT 0,
    "IDGROUPE" BIGINT DEFAULT 0,
    "IDCLASSES" BIGINT DEFAULT 0);

-- Création de la table NOTES
CREATE TABLE "NOTES" (
    "IDNOTES" SERIAL8  PRIMARY KEY ,
    "MOYCLASSE" REAL DEFAULT 0,
    "NOTESCOMPOS" REAL DEFAULT 0,
    "APRECIATION" VARCHAR(50) ,
    "MOYGENERALE" REAL DEFAULT 0,
    "MOYCOEFF" REAL DEFAULT 0,
    "NOTECLASSE1" REAL DEFAULT 0,
    "NOTECLASSE2" REAL DEFAULT 0,
    "IDMATIEREENSEIGNE" BIGINT ,
    "IDENSEIGNANT" BIGINT ,
    "IDELEVES" BIGINT ,
    "IDEVALUTION" BIGINT ,
    "VISAENSIGNANT" BOOL DEFAULT false,
    "VISADIRECTION" BOOL DEFAULT false,
    "IDUTILISATEURS" BIGINT DEFAULT 0,
    "DISPENSE" BOOL DEFAULT false);

-- Création de la table EVALUTION
CREATE TABLE "EVALUTION" (
    "IDEVALUTION" SERIAL8  PRIMARY KEY ,
    "IDANNEESCOLAIRE" BIGINT DEFAULT 0,
    "EVALUATION" VARCHAR(100) ,
    "IDCLASSES" BIGINT DEFAULT 0,
    "DATEEVALUATION" DATE ,
    "STATUS" SMALLINT DEFAULT 0,
    "PERIODE" SMALLINT DEFAULT 0,
    "CLOTURE" BOOL DEFAULT false,
    "IDNIVEAU" BIGINT DEFAULT 0,
    "IDTYPEEVALUATION" BIGINT );

-- Création de la table TYPEFRAIS
CREATE TABLE "TYPEFRAIS" (
    "IDTYPEFRAIS" SERIAL8  PRIMARY KEY ,
    "TYPEFRAIS" VARCHAR(50) );

-- Création de la table FRAISCLASSES
CREATE TABLE "FRAISCLASSES" (
    "IDFRAISCLASSES" SERIAL8  PRIMARY KEY ,
    "MONTANT" NUMERIC(24,6) DEFAULT 0,
    "IDTYPEFRAIS" BIGINT ,
    "IDCLASSES" BIGINT ,
    "MENSUEL" BOOL DEFAULT false,
    "MONTANTMENSUEL" NUMERIC(24,6) DEFAULT 0,
    "MONTANTANNUEL" NUMERIC(24,6) DEFAULT 0);

-- Création de la table INSCRIPTION
CREATE TABLE "INSCRIPTION" (
    "IDINSCRIPTION" SERIAL8  PRIMARY KEY ,
    "N_MATRICULE" VARCHAR(100) ,
    "MONTANTAPAYER" NUMERIC(24,6) DEFAULT 0,
    "IDANNEESCOLAIRE" BIGINT DEFAULT 0,
    "DATEINSCRIPTION" DATE ,
    "STATUS" SMALLINT DEFAULT 0,
    "IDELEVES" BIGINT ,
    "IDCLASSES" BIGINT ,
    "IDGROUPE" BIGINT DEFAULT 0,
    "IDCATEGORIE" BIGINT DEFAULT 0,
    "MONTANTPAYER" NUMERIC(24,6) DEFAULT 0,
    "IDFRAISINSCRIPTION" BIGINT ,
    "MONTANTMENSUEL" NUMERIC(24,6) DEFAULT 0,
    "MONTANTINSCRIPTION" NUMERIC(24,6) DEFAULT 0,
    "IDNIVEAU" BIGINT DEFAULT 0,
    "MOYENNEANNUELLE" INTEGER DEFAULT 0,
    "PASSEENCLASSESUP" BOOL DEFAULT false,
    "TOUTREGLET" BOOL DEFAULT false);

-- Création de la table PAYEMENT
CREATE TABLE "PAYEMENT" (
    "IDPAYEMENT" SERIAL8  PRIMARY KEY ,
    "IDANNEESCOLAIRE" BIGINT DEFAULT 0,
    "IDCLASSES" BIGINT DEFAULT 0,
    "IDINSCRIPTION" BIGINT ,
    "DATE" DATE ,
    "HEURE" TIME ,
    "PERSONNECONTACT" VARCHAR(50) ,
    "PERIODE" SMALLINT DEFAULT 0,
    "IDUTILISATEURS" BIGINT DEFAULT 0,
    "MONTANT" NUMERIC(24,6) DEFAULT 0,
    "IDTYPEFRAIS" BIGINT DEFAULT 0);

-- Création de la table UTILISATEURS
CREATE TABLE "UTILISATEURS" (
    "IDUTILISATEURS" SERIAL8  PRIMARY KEY ,
    "NOMPRENOM" VARCHAR(100) ,
    "CATEGORIE" VARCHAR(50) ,
    "LOGIN" VARCHAR(50)  UNIQUE ,
    "MOTDEPASSE" VARCHAR(50) ,
    "MATRICULE" VARCHAR(50) ,
    "DATECREATION" DATE ,
    "DROIT" INTEGER DEFAULT 0,
    "BLOQUE" BOOL DEFAULT false,
    "IDPROFIL" BIGINT ,
    "SUPPRIMER" BOOL DEFAULT false);

-- Contraintes d'intégrité
ALTER TABLE "INSCRIPTION" ADD FOREIGN KEY ("IDELEVES") REFERENCES "ELEVES" ("IDELEVES");
ALTER TABLE "INSCRIPTION" ADD FOREIGN KEY ("IDANNEESCOLAIRE") REFERENCES "ANNEESCOLAIRE" ("IDANNEESCOLAIRE");
ALTER TABLE "INSCRIPTION" ADD FOREIGN KEY ("IDCLASSES") REFERENCES "CLASSES" ("IDCLASSES");
ALTER TABLE "CLASSES" ADD FOREIGN KEY ("IDNIVEAU") REFERENCES "NIVEAU" ("IDNIVEAU");
ALTER TABLE "MATIEREENSEIGNE" ADD FOREIGN KEY ("IDMATIERE") REFERENCES "MATIERE" ("IDMATIERE");
ALTER TABLE "MATIEREENSEIGNE" ADD FOREIGN KEY ("IDCLASSES") REFERENCES "CLASSES" ("IDCLASSES");
ALTER TABLE "COURS" ADD FOREIGN KEY ("IDMATIEREENSEIGNE") REFERENCES "MATIEREENSEIGNE" ("IDMATIEREENSEIGNE");
ALTER TABLE "COURS" ADD FOREIGN KEY ("IDENSEIGNANT") REFERENCES "ENSEIGNANT" ("IDENSEIGNANT");
ALTER TABLE "NOTES" ADD FOREIGN KEY ("IDMATIEREENSEIGNE") REFERENCES "MATIEREENSEIGNE" ("IDMATIEREENSEIGNE");
ALTER TABLE "NOTES" ADD FOREIGN KEY ("IDELEVES") REFERENCES "ELEVES" ("IDELEVES");
ALTER TABLE "NOTES" ADD FOREIGN KEY ("IDEVALUTION") REFERENCES "EVALUTION" ("IDEVALUTION");
ALTER TABLE "PAYEMENT" ADD FOREIGN KEY ("IDINSCRIPTION") REFERENCES "INSCRIPTION" ("IDINSCRIPTION");
ALTER TABLE "FRAISCLASSES" ADD FOREIGN KEY ("IDTYPEFRAIS") REFERENCES "TYPEFRAIS" ("IDTYPEFRAIS");
ALTER TABLE "FRAISCLASSES" ADD FOREIGN KEY ("IDCLASSES") REFERENCES "CLASSES" ("IDCLASSES");